language: ruby
rvm:
  - 1.9.3
env:
  - NOCOV=true
  - PA_ORM=mongoid
services:
  - mongodb
matrix:
  allow_failures:
    - rvm: 2.0.0
  include:
    - rvm: 2.0.0
      env: "NOCOV=true WITH_PRIDE=true"
email:
  recipients:
    - piotrek@okonski.org
    - jakub@okonski.org
  on_success: change
  on_failure: always
