language: ruby
rvm:
  - 1.9.3
  - 2.0.0
env:
  - NOCOV=true
  - NOCOV=true PA_ORM=mongoid
  - NOCOV=true PA_ORM=mongoid PA_PURGE=true
services:
  - mongodb
email:
  recipients:
    - piotrek@okonski.org
    - jakub@okonski.org
  on_success: change
  on_failure: always
