language: ruby
rvm:
  - 2.2.6
  - 2.3.3
  - 2.4.0
matrix:
  include:
    - rvm: 2.2.6
      gemfile: gemfiles/Gemfile.rails-3.X
      env: PA_ORM=active_record
    - rvm: 2.2.6
      gemfile: gemfiles/Gemfile.rails-4.0
      env: PA_ORM=active_record
    - rvm: 2.3.3
      gemfile: gemfiles/Gemfile.rails-4.0
      env: PA_ORM=active_record
    - rvm: 2.4.0
      gemfile: gemfiles/Gemfile.rails-5.0
      env: PA_ORM=active_record
    - rvm: 2.2.26
      env: PA_ORM=mongoid
env:
  - PA_ORM=active_record
  - PA_ORM=mongo_mapper
services:
  - mongodb
email:
  recipients:
    - piotrek@okonski.org
    - jakub@okonski.org
  on_success: change
  on_failure: always
