language: ruby
rvm:
  - 2.1.8
  - 2.2.4
matrix:
  include:
    - rvm: 2.1.8
      gemfile: gemfiles/Gemfile.rails-3.X
      env: PA_ORM=active_record
    - rvm: 2.1.8
      gemfile: gemfiles/Gemfile.rails-4.0
      env: PA_ORM=active_record
    - rvm: 2.2.4
      gemfile: gemfiles/Gemfile.rails-4.0
      env: PA_ORM=active_record
    - rvm: 2.2.4
      gemfile: gemfiles/Gemfile.rails-5.0
      env: PA_ORM=active_record
    - rvm: 2.1.8
      env: PA_ORM=mongoid
env:
  - PA_ORM=active_record
  - PA_ORM=mongo_mapper
services:
  - mongodb
email:
  recipients:
    - piotrek@okonski.org
    - jakub@okonski.org
  on_success: change
  on_failure: always
