language: ruby
rvm:
  - 1.9.2
  - 1.9.3
  - 2.0.0-preview1
env:
  - NOCOV=true
matrix:
  allow_failures:
    - rvm: 2.0.0-preview1
email:
  recipients:
    - piotrek@okonski.org
    - jakub@okonski.org
  on_success: change
  on_failure: always
